### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by Gr3q** [JustinTimperio/pacback#11]
Hello, I made a PKGBUILD for pacback. I think it could drive interest and help if you had it up on AUR.

```bash
pkgname=pacback-git
pkgver=r56.77b20b3
pkgrel=1
pkgdesc='Advanced Rollback Version Control for Arch Linux - Alpha'
arch=('any')
url='https://github.com/JustinTimperio/pacback'
license=('MIT')
provides=('pacback')
depends=('python-tqdm' 'arch-install-scripts')

pkgver() {
  cd "${srcdir}/pacback"
  # Get the version number.
  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

prepare() {
  git clone --recurse-submodules https://github.com/JustinTimperio/pacback.git
}

package() {
  cd "${srcdir}/pacback"
  install -dm 755 "${pkgdir}"/{usr/share/pacback,usr/bin/}
  cp -dr --no-preserve='ownership' core "${pkgdir}"/usr/share/pacback
  #install -dm 755 core "${pkgdir}"/usr/share/pacback
  ln -sf /usr/share/pacback/core/pacback.py "${pkgdir}"/usr/bin/pacback
}
```

I can upload it to AUR and make you Co-Maintainer but you can also upload it yourself or not upload it at all, it's up to you to decide.

**Comment by JustinTimperio** [comment]
Thanks for the awesome work here! Been swamped at work but I'm hoping to merge my refactor branch in the next couple days. I haven't done this yet because I have been making some pretty major changes to the core. Once I get it cleaned up and tested I'll add this to the AUR.

**Comment by Gr3q** [comment]
Great, that's ok. The PKBUILD works for me (I'll keep using it until the release then).

**Comment by JustinTimperio** [comment]
So I have merged my refactor branch and I am very happy with it so far. I would like to see if anyone submits bugs but if not I think this is ready for a AUR package. 

The real issue is upgrading to a AUR package from a manual install. Not sure how to approach this but will start looking into it.

**Comment by JustinTimperio** [comment]
Thanks for the help here. Closing this out

https://aur.archlinux.org/packages/pacback-git/
https://aur.archlinux.org/packages/pacback/
