### ISSUE TITLE
Feature Request: Add "List all restore points" as an option

### ISSUE THREAD

**Issue by Gr3q** [JustinTimperio/pacback#12]
What is says in the title. Maybe using ```-l```?

**Comment by JustinTimperio** [comment]
I'm planning on adding this soon along with a remove function. (maybe -del or -rm) I have been working on a pretty major overhaul, so this should be simple once everything is working. If you want to see the status of this, checkout to the refactor fork. I still need to do a lot more unit testing before I merge it though.

**Comment by JustinTimperio** [comment]
Okay so I just added this feature in the refactor fork. I will try and merge this branch soon

**Comment by Gr3q** [comment]
Thanks, I can wait until the merge

**Comment by JustinTimperio** [comment]
Hey Gr3q,
I'm looking for some help testing my refactor before I merge it. If you have any interest in doing so let me know.

Thanks

**Comment by Gr3q** [comment]
Sure, I can do that, let me know what to test for and I'll do it

**Comment by JustinTimperio** [comment]
Thanks, I appreciate the help. Version 1.6 is a massive refactor from 1.5. While the commands are the same under the hood, things are far more refined from a code perspective. I'm putting the final touches on the update before I merge.

- General Bug checking is the main thing I need to do. Now that the project is getting large, it makes it much harder for me to test all the branches that could execute. I have been putting it through the paces as much as I can but I have had pretty limited time.

- The pacman hook seems to be working but I would like someone other than me to confirm that it is working. 

- I have looked through the code a bunch and as far as I can tell the zst update hasn't affected anything. Now that it's fully released this can be tested fully. (Not really expecting any issues)

- Costly string comparisons and regex filters are now multi-threaded. This should reduce runtime quite a bit but I want to make sure it's not locking up on slower cpu's.

- Individual package searches are far more accurate but the regex is a little hacky. I want to make sure it works effectively for most package names.

- There is a new clean function that automates a lot of the maintenance of clearing caches and restore points. I have only done limited testing on this.

**Comment by Gr3q** [comment]
I can do point number 2, 3, 4  on 2 computers quite easily. Number 5 (and maybe 1?) sounds like it could use unit tests rather than manual testing tho.

For number 1 and 6 you will have to specify what to test for and I will do them.

**Comment by JustinTimperio** [comment]
Unfortunately, most of the testing needs to be done manually. I use flake8 to look for issues but a lot of the system commands just need to be tested manually. 

I have finished 1, 3, 4, 5, 6

I think I'm going to merge this unless you have found any serious errors I have missed.

**Comment by JustinTimperio** [comment]
Since the list feature is now added I'm going to close this.
