### ISSUE TITLE
KeyboardInterrupt error is not handled nicely

### ISSUE THREAD

**Issue by Gr3q** [JustinTimperio/pacback#18]
**Describe the Bug:**\
App does not handle KeyboardInterrupts too nicely. Not an urgent matter

**Output of Command**
It looks like this
```bash
Do You Want to Remove These Packages From Your System? (y/n):^CTraceback (most recent call last):
  File "/usr/bin/pacback", line 115, in <module>
    rb.rollback_to_rp(version, args.rollback)
  File "/usr/share/pacback/core/rollback_rp.py", line 162, in rollback_to_rp
    if PS.YN_Frame('Do You Want to Remove These Packages From Your System?') is True:
  File "/usr/share/pacback/core/python_scripts/ps_defuns.py", line 58, in YN_Frame
    yn = input('\033[1m' + prompt + ' (y/n):' + '\033[0m')
KeyboardInterrupt

```

**Machine (please fill in the following information):**
 - Kernel Version: Linux gr3q-desktop 5.4.11-arch1-1 #1 SMP PREEMPT Sun, 12 Jan 2020 12:15:27 +0000 x86_64 GNU/Linux
 - Python Version: Python 3.8.1
 - Install Type: pacback
 - Pacback Version: Pacback Version: 1.6.1

**To Reproduce**
1. Do a rollback
2. Press Ctrl+C

**Expected behavior**
Exit without errors

**Comment by JustinTimperio** [comment]
Sorry for the slow response. I think I was expecting people to input 'no' instead of  'ctrl+c'. I will take a look at this since I expect there are a number of places where the program doesn't exit cleanly.

**Comment by JustinTimperio** [comment]
This has not been forgotten! This will be fixed in the full release which hopefully will be in the next week or two.

**Comment by JustinTimperio** [comment]
This feature is now present in the latest release
