### ISSUE TITLE
Automatic sudo is not handled correctly

### ISSUE THREAD

**Issue by Gr3q** [JustinTimperio/pacback#19]
**Describe the Bug:**\
If pacback has started without sudo, sudo is asking for password, but pacback still throws the error that it must be ran as sudo

**Output of Command**
- Output sent to the user in terminal
```bash
gr3q@gr3q-desktop ~> pacback -v
[sudo] password for gr3q: 
Pacback Must Be Run With Sudo OR As Root!
```

- Log output in /var/log/pacback.log
```
2020/01/18-12:29:04.476195 : PreFlight : Started Logging Session
2020/01/18-12:29:04.486911 : PreFlight : Not Root!
2020/01/18-12:29:04.498016 : PreFlight : Ended Logging Session

```

**Machine (please fill in the following information):**
 - Kernel Version: Linux gr3q-desktop 5.4.11-arch1-1 #1 SMP PREEMPT Sun, 12 Jan 2020 12:15:27 +0000 x86_64 GNU/Linux
 - Python Version: Python 3.8.1
 - Install Type: pacback
 - Pacback Version: Pacback Version: 1.6.1

**To Reproduce**
1. Run any pacback command without sudo with user account
2. Enter password
3. Observe

**Expected behavior**
The sudo should have been picked up by pacback

**Comment by JustinTimperio** [comment]
So I noticed this myself but have still been unable to trace which command is actually asking for sudo. I think it may be the way I am checking to see if the command is executed as root.

**Comment by JustinTimperio** [comment]
I apologize for the slow response here. Been on the road traveling so I haven't had the time to look at this fully. So this was actually a very simple issue. Sudo was being rasied to write the error out to a log in /var. I'm going to remove this feature and push it downstream along with some other patches in V1.7.

**Comment by Gr3q** [comment]
Thats ok, there is no need to to patch just for me, I can wait.

**Comment by JustinTimperio** [comment]
This has not been forgotten! This will be fixed in the full release which has a session management system that will handle these errors.

**Comment by JustinTimperio** [comment]
This bug can finally be squashed
