### ISSUE TITLE
Add option to tag/label restore points

### ISSUE THREAD

**Issue by Gr3q** [JustinTimperio/pacback#20]
**Describe the solution you'd like**
Add a ```--label``` option or something when the restore point is created manually, also show the label if exist in ```-l```, ```-rb``` and such.

Would add some context on why an user created it (or if its an automatic point creation, add that as well).

**Comment by JustinTimperio** [comment]
https://github.com/JustinTimperio/pacback#flags-and-utils

So you can do that already with `--notes` but it won't show the note when you do `-l`. I'll change it so it shows notes, but if you call `--info` that will show the note. 
A proper label system would be nice but I have some bigger features I want to add first.

**Comment by JustinTimperio** [comment]
This has now been added
