### ISSUE TITLE
ModuleNotFoundError: No module named 'rich'

### ISSUE THREAD

**Issue by muralikodali** [JustinTimperio/pacback#28]
when i tried to execute `pacback -c 1` , it gives following error output  :  

```
Traceback (most recent call last):
  File "/usr/bin/pacback", line 9, in <module>
    import user
  File "/usr/share/pacback/core/user.py", line 4, in <module>
    from rich.table import Table
ModuleNotFoundError: No module named 'rich'
```
python-rich package is installed.

**Comment by JustinTimperio** [comment]
Hi, 
I need at least the following information described in the bug report template to diagnosis this.

Kernel Version: (uname -r)
Python Version: (python3 --version)
Python Rich Version (pacman -Q | grep python-rich)
Python Requests Version (pacman -Q | grep python-requests)
Pacback Version: (sudo pacback -v)
Install Type: (pacback vs pacback-git)

**Comment by muralikodali** [comment]
Kernel Version :  5.4.60-1-lts
Python Version:  Python 3.7.3
Python Rich Version : python-rich 6.0.0-1
Python Requests Version : python-requests 2.24.0-1 python-requests-file 1.5.1-1
Pacback Version : giving error output as given above
Install Type :  pacback (git clone https://aur.archlinux.org/pacback.git)

**Comment by JustinTimperio** [comment]
So I have been unable to reproduce this issue across multiple machines. You have all the correct packages and this should work unless python-rich itself is installed incorrectly. 

1. What AUR helper are you using? 
2. If you open and python repl then type `import rich` do you still get the same error?

**Comment by muralikodali** [comment]
using ipython ;
import rich is showing no error. 

it may be problem from my side. I will try to find out.

**Comment by muralikodali** [comment]
after cd in to pacback directory after cloning; i have run
import rich;
afterwards issued command makepkg -si and installed pacback successfully.
