### ISSUE TITLE
No snapshots being made

### ISSUE THREAD

**Issue by wabunting** [JustinTimperio/pacback#36]
I have a mostly working up-to-date installation of pacback (not pacback-git) from the AUR--creating and restoring to restore points works--but no snapshots are being generated, whether I use paru or pacman directly.

![image](https://user-images.githubusercontent.com/42874530/187883386-f4a0f2dd-c672-498e-acb8-c64d4c578936.png)

**Comment by JustinTimperio** [comment]
Check out the user docs. Snapshots are not the same as restore points. 
https://github.com/JustinTimperio/pacback/blob/master/USER_GUIDE.md#creating-permanent-restore-points

**Comment by wabunting** [comment]
Sorry, I may be missing something obvious, or equally likely have not explained myself well. I have read these docs-I thought snapshots are automatically generated whenever pacman installs or updates a package. This is my issue-updating or installing software using pacman or paru does not generate snapshots, or at least does not generate snapshots that pacback -ls reports.

**Comment by JustinTimperio** [comment]
Ahhh I see, I miss read this in my early morning stupor. So potentially something is messed up with the pacman hook? Basically, a hook gets injected by the package on installation that then allows pacman to keep track of the states. Could you give me some context about what is going on? Just fill something like this out and I can take a look

https://github.com/JustinTimperio/pacback/blob/master/.github/ISSUE_TEMPLATE/pacback-bug-report-template.md

**Comment by wabunting** [comment]
Sure, thanks!

**Describe the Bug:**
Snapshots not being generated as above.

**Output of Command:**
Generating and restoring from light restore points works completely as expected-I set an RP, installed a package, and then restored to the RP successfully
pacback -ls displays the light restore points generated, but lists snapshots as NONE
Attempting to restore from snapshot 01 anyways (in case ls just isn't working) gives a FileNotFoundError:
`FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/pacback/snapshots/ss01.meta'`

[pacback.log](https://github.com/JustinTimperio/pacback/files/9480195/pacback.log)
There's no /etc/pacback/config file, but here's /etc/pacback.conf (as a txt file, since github threw a fit): 
[pacback.conf.txt](https://github.com/JustinTimperio/pacback/files/9480227/pacback.conf.txt)

Kernel version: 5.19.4-arch1-1-t2 (I'm using a modified kernel for Arch Linux on a Macbook with a T2 chip)
Python version: 3.10.6
Python-rich version: 12.5.1-1
Python-requests version: 2.28.1-1
Pacback Version: 2.1.0
PAF Version: 412fd69
Install type: pacback, not pacback-git

**To reproduce:**
Install or update a package with pacman, then execute pacback -ls

**Expected behaviour:**
I'd hope to see a new snapshot in the snapshot column, but instead I see none.

**Screenshots:**
See above.

**Comment by JustinTimperio** [comment]
So looking at this, i see some things that i think are sus but first can your try the following 
```
--install_hook | Install a pacman hook that creates a snapshot during each pacman transaction.
Example: pacback --install_hook
```

**Comment by wabunting** [comment]
That worked, thanks!
![image](https://user-images.githubusercontent.com/42874530/188259807-e4998107-39b9-4daf-af0b-b22f97a35b3e.png)
