### ISSUE TITLE
Can't create restore point

### ISSUE THREAD

**Issue by PocketSam** [JustinTimperio/pacback#5]
Hello.

Probably I'm missing something, but after installing your application I can't create a restore point.

I've created a /restore-point folder and cloned repository there, made a simlink.
After that I try to create a restore point:

sudo pacback -c 1
Building Light Restore Point...
Traceback (most recent call last):
File "/usr/bin/pacback", line 466, in <module>
create_restore_point(args.create_rp, args.full_rp, args.add_dir)
File "/usr/bin/pacback", line 132, in create_restore_point
export_list(rp_path + '.meta', meta_list)
File "/restore-points/pacback/core/python_scripts/ps_linux.py", line 52, in export_list
with open(file_name, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/restore-points/pacback/restore-points/rp01.meta'

I would be glad if you explain me where I'm wrong. I've read help but can't get what I'm missing. 

Thanks!

**Comment by JustinTimperio** [comment]
Mmmmmm so it looks like you didn't create the directory in the right place. I'll just automate the creation of this folder in the next patch. 

The output shows '/restore-points/pacback/restore-points/rp01.meta' as the output file but its nested. 

1. To fix this issue navigate to the base directory where you cloned pacback
2. Create a folder called restore-points inside the pacback directory
3. Open the permissions on the restore point folder just incase. 

Your directory structure should now look like this.
├── pacback
│   ├── core
│   │   ├── pacback.py
│   │   └── python_scripts
│   │       ├── __init__.py
│   │       ├── LICENSE
│   │       ├── other
│   │       │   ├── gztar_bash.py
│   │       │   └── gztar.py
│   │       ├── ps_archives.py
│   │       ├── ps_defuns.py
│   │       ├── ps_linux.py
│   │       ├── ps_modules.py
│   │       ├── ps_networking.py
│   │       └── __pycache__
│   │           ├── __init__.cpython-38.pyc
│   │           ├── ps_archives.cpython-38.pyc
│   │           ├── ps_defuns.cpython-38.pyc
│   │           ├── ps_linux.cpython-38.pyc
│   │           ├── ps_modules.cpython-38.pyc
│   │           └── ps_networking.cpython-38.pyc
│   ├── LICENSE
│   ├── README.md
│   └── restore-points
│       ├── rp00.meta
│       └── rp01.meta

**Comment by JustinTimperio** [comment]
So I just pushed an update that will automatically create this folder for you. 

Just git pull the updates and you should be good to go. Let me know if everything works and I'll close this issue.

**Comment by PocketSam** [comment]
Yes. Now it works! Thanks!
